name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/change-name ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - name: setup
        run: |
          source /etc/profile && source /etc/sysdenv
          load-pyenv
          python -v; which python
          REPO="ds-pyhocon"
          PY_REPO_VERSION="$REPO"_runner"${{ matrix.python-version }}"
          echo $PY_REPO_VERSION
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv $PY_REPO_VERSION && pyenv local $PY_REPO_VERSION
          PYENV_ROOT_VAR="/home/ec2-user/.pyenv/versions/$PY_REPO_VERSION"
          echo "$PYENV_ROOT_VAR/bin:/home/ec2-user/.local/bin:$PATH" >> $GITHUB_PATH
      - name: Pip Install Build Tools
        run: |
          which pip
          pip install --upgrade build twine
      - name: Build
        run: |
          which python
          python -m build