name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/test-centos ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6.0, 3.7.0, 3.8.0, 3.9.0 ]
    steps:
      - name: setup
        run: |
          source /etc/profile && source /etc/sysdenv
          ls
          load-pyenv
          python -v; which python
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv runner${{ matrix.python-version }} && pyenv local runner${{ matrix.python-version }}
          export PYENV_ROOT="/home/ec2-user/.pyenv/versions/runner${{ matrix.python-version }}/"
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/bin:/home/ec2-user/.local/bin:$PATH" >> $GITHUB_PATH
          echo "after pyenv install, check python and pip version"
          which python
          which pip
      - name: Pip Install Build Tools
        run: |
          echo $PYENV_ROOT
          echo $GITHUB_PATH
          echo $PATH
          which pip
          which python
          pip install --upgrade build twine
      - name: Build
        run: |
          echo $PYENV_ROOT
          echo $GITHUB_PATH
          echo $PATH
          which pip
          which python
          python -m build
