name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/test-centos ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v3
#    - name: Set up Python
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
#      env:
#        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Ensure pip is linked to pip3
      if: true # disabled on eks self-hosted runners, enabled on asg self-hosted runners
      shell: bash
      run: |
        echo $RUNNER_TOOL_CACHE
    - name: Pip Install Build Tools
      run: pip install --upgrade build twine
    - name: Build
      run: python -m build
