name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/test-centos ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - name: setup
      id: setup
      run: |
        ls
        source /etc/profile && source /etc/sysdenv
        echo "log"
        load-pyenv
        echo "log2"
        python -v; which python
        echo "log3"
        pyenv install ${{ matrix.python-version }} -s
        echo "log2"
        pyenv virtualenv runner${{ matrix.python-version }} && pyenv local runner${{ matrix.python-version }}
        echo "log5"
        export PYENV_ROOT="/home/ec2-user/.pyenv/versions/runner${{ matrix.python-version }}/"
        export PATH="$PYENV_ROOT/bin:/home/ec2-user/.local/bin:$PATH"
        echo "after pyenv install, check python and pip version"
        which python
        which pip
        exit 0
    - name: Pip Install Build Tools
      run: pip install --upgrade build twine
    - name: Build
      run: python -m build
