name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/change-name ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: dspyhocon${{ matrix.python-version }}
      - name: setup
        run: |
          cd dspyhocon${{ matrix.python-version }}
          source /etc/profile && source /etc/sysdenv
          load-pyenv
          python -v; which python
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv-delete dspyhoconrunner${{ matrix.python-version }} && pyenv virtualenv dspyhoconrunner${{ matrix.python-version }} && pyenv local dspyhoconrunner${{ matrix.python-version }}
          PYENV_ROOT="/home/ec2-user/.pyenv/versions/dspyhoconrunner${{ matrix.python-version }}"
          echo "$PYENV_ROOT/bin:/home/ec2-user/.local/bin:$PATH" >> $GITHUB_PATH
      - name: Pip Install Build Tools
        run: |
          which pip
          pip install --upgrade build twine
      - name: Build
        run: |
          which python
          python -m build