name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/test-centos ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6.0, 3.7.0, 3.8.0, 3.9.0 ]
    env:
      PATH: /home/ec2-user/.pyenv/versions/runner${{ matrix.python-version }}/bin:/home/ec2-user/.local/bin:${PATH}
    steps:
      - name: setup
        run: |
          source /etc/profile && source /etc/sysdenv
          ls
          load-pyenv
          python -v; which python
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv runner${{ matrix.python-version }} && pyenv local runner${{ matrix.python-version }}
          echo "after pyenv install, check python and pip version"
          echo $PATH
          which python
          which pip
      - name: Pip Install Build Tools
        run: |
          echo $PATH
          which pip
          which python
          pip install --upgrade build twine
      - name: Build
        run: python -m build
