name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] #TODO: should be removed
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    env:
      repo: dspyhocon
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup
        run: |
          source /etc/machine && load-pyenv

          # pyenv requires python version accurates to minor, so 3.8 => 3.8.16 and 3.8.12 => 3.8.12
          PYTHON_VERSION=$(pyenv latest -k ${{ matrix.python-version }})

          # install python version
          pyenv install $PYTHON_VERSION -s

          # recreate virtual env and activate the virtual env
          VIRTUAL_ENV=${{ env.repo }}"_"${{ runner.name }}"_"$PYTHON_VERSION
          pyenv virtualenv-delete -f $VIRTUAL_ENV
          pyenv virtualenv $PYTHON_VERSION $VIRTUAL_ENV
          pyenv local $VIRTUAL_ENV
      - name: Pip Install Build Tools
        run: |
          source /etc/machine && load-pyenv
          pip install --upgrade build twine
      - name: Build
        run: |
          source /etc/machine && load-pyenv
          python -m build
      - name: Publish
        run: |
          source /etc/machine && load-pyenv
          twine upload --repository-url $ARTIFACTORY_URL dist/* -u $ARTIFACTORY_ROLE -p $ARTIFACTORY_AUTH
